// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWU1KAJFHkFmlaQt4lhREjYREvaqfJnw',
    appId: '1:605281409116:web:33afa7ca4a901eac97ae99',
    messagingSenderId: '605281409116',
    projectId: 'flutterapp-74e0e',
    authDomain: 'flutterapp-74e0e.firebaseapp.com',
    databaseURL: 'https://flutterapp-74e0e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-74e0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__xEk3A3BX0VPw7ouAaToYX6OCWVvDu0',
    appId: '1:605281409116:android:c0949c0b54c0e11797ae99',
    messagingSenderId: '605281409116',
    projectId: 'flutterapp-74e0e',
    databaseURL: 'https://flutterapp-74e0e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-74e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCICZ8KtqvUy8gr-y-_s7zVTT1K-ok-lc',
    appId: '1:605281409116:ios:d0808f6e9019796f97ae99',
    messagingSenderId: '605281409116',
    projectId: 'flutterapp-74e0e',
    databaseURL: 'https://flutterapp-74e0e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-74e0e.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCICZ8KtqvUy8gr-y-_s7zVTT1K-ok-lc',
    appId: '1:605281409116:ios:d0808f6e9019796f97ae99',
    messagingSenderId: '605281409116',
    projectId: 'flutterapp-74e0e',
    databaseURL: 'https://flutterapp-74e0e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-74e0e.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0rIx4BTXy-wNh_qdon5TDdklBst8iVR0',
    appId: '1:605281409116:web:a14fdbeba06ca8fc97ae99',
    messagingSenderId: '605281409116',
    projectId: 'flutterapp-74e0e',
    authDomain: 'flutterapp-74e0e.firebaseapp.com',
    databaseURL: 'https://flutterapp-74e0e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-74e0e.firebasestorage.app',
  );
}
